### ISSUE TITLE
find_optional_project

### ISSUE THREAD

**Issue by kgish** [opf/openproject-proto_plugin#11]
In the kittens controller, we have:
```
# this is necessary if you want the project menu in the sidebar for your view
before_filter :find_optional_project, only: :index
```
Needs to be documented and explained properly.

**Comment by oliverguenther** [comment]
Fixed in https://github.com/opf/openproject-proto_plugin/commit/879df4daba43e22349eab596ac805290843a9d11 which now turns kittens module into a proper project module
