### ISSUE TITLE
Update for newer openproject version

### ISSUE THREAD

**Issue by trombipeti** [opf/openproject-proto_plugin#15]
The frontend doesn't work on openproject version 8.2.0.
I beleive it's because frontend/app hasn't been renamed to frontend/legacy-app.
Now as a poor developer who knows only a little about RoR/Angular/all that stuff but has been assigned a task to develop a custom openproject plugin, it has caused me several days to figure out, why my very simple plugin stopped working after upgrading openproject.

So for the future, it could be a good thing if this prototype plugin actually demonstrated how a plugin should look like for the latest version of openproject.

Thank you!

**Comment by oliverguenther** [comment]
Fixed in https://github.com/opf/openproject-proto_plugin/commit/879df4daba43e22349eab596ac805290843a9d11
